<?php

/**
 * Export Product data to xml data
 *
 * @category   OnlineBiz
 * @package    OnlineBiz_Facebookstore
 * @author     Nguyen Viet Tung (http://onlinebizsoft.com)
 */
?>
<script type="text/javascript">
//<![CDATA[
  productShowImage = function(src, title) {
		$("swap-image").setAttribute('src', src);
		$("swap-image").setAttribute('alt', title);
		$("swap-image").setAttribute('title', title);	
	};
//]]>
</script>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');

	$image_size = 275;
	$thumnail_size = 60;
	
?>

<p class="product-image">
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(735); ?>" 
            rel="lightbox[rotation]" 
            title="<?php echo $this->htmlEscape($this->getImageLabel()); ?>"
            onclick="return false;"
        >
	
    <?php
        $_img = '<img id="swap-image" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($image_size).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?></a>
</p>

<?php if (count($this->getGalleryImages()) > 1): ?>
<div id="more-view">
<?php echo $this->__('More Views') ?>
</div>
<div class="more-view-gallery">
<?php foreach ($this->getGalleryImages() as $_image): ?>
	<?php if($_image->getFile()!=$_product->getImage()):?>
	<?php
	$subtitle = $this->htmlEscape($_image->getLabel());
	if(empty($subtitle))
	        $subtitle  = $_product->getName();
	?>
	<div class="item">
		<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(735, 735); ?>" 
            rel="lightbox[rotation]" 
            title="<?php echo $subtitle; ?>"
            onclick="return false;"
        >

		<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($thumnail_size); ?>" width="<?php echo $thumnail_size?>" height="<?php echo $thumnail_size;?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
</a>
	</div>
	<?php endif;?>
<?php endforeach; ?>
</div>
<?php endif; ?>
<script type="text/javascript">
function initLightbox(){
    new Lightbox({
        fileLoadingImage: '<?php echo $this->getSkinUrl('onlinebizsoft/facebookstore/images/fbloading.gif') ?>',
        fileBottomNavCloseImage: '<?php echo $this->getSkinUrl('onlinebizsoft/facebookstore/images/fbcloselabel.gif') ?>',
        overlayOpacity: '0.8',
        animate: '1',
        resizeSpeed: '5',
        borderSize: '10',
        labelImage: 'Image',
        labelOf: 'of'
    });
}


if (Prototype.Browser.IE) {
    Event.observe(window, 'load', function(){ //KB927917 fix
        initLightbox();
    });
} else {
    document.observe("dom:loaded", function(){
        initLightbox();
    });
}
</script>