<?php
$installer = $this;
$installer->startSetup();
$installer->addAttribute('catalog_product', 'blacknwhite_prbrand', array(
    'group'         => 'Meigee - Blacknwhite options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product Brand Image',
    'note' => 'Allows to display brand image on product pages',
    'source'            => 'ThemeOptionsBlacknwhite/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 11,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'blacknwhite_prbrandlink', array(
    'group'         => 'Meigee - Blacknwhite options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Link to brand search',
    'note' => 'Image will refer to search products by brand',
    'source'            => 'ThemeOptionsBlacknwhite/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 12,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'blacknwhite_prbrandtarget', array(
    'group'         => 'Meigee - Blacknwhite options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Link target blank',
    'note' => 'Choose "Enable" if you want open links in a new tab',
    'source'            => 'ThemeOptionsBlacknwhite/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 13,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'blacknwhite_prbrandpos', array(
    'group'         => 'Meigee - Blacknwhite options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Brand Image Position',
    'note' => 'Choose where your brand image will be shown',
    'source'            => 'ThemeOptionsBlacknwhite/attribute_source_brandpos',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 14,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_product', 'blacknwhite_prsidebar', array(
    'group'         => 'Meigee - Blacknwhite options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product Page Sidebar',
    'note' => 'Choose if you want sidebar to be shown on a product page',
    'source'            => 'ThemeOptionsBlacknwhite/attribute_source_productsidebar',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 15,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'manufacturer_info', array(
    'group'         => 'General',
    'input'         => 'textarea',
    'type'          => 'text',
    'label'         => 'Manufacturer Info',
    'note' => 'Will be displayed with manufacturer image',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 99,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->endSetup();