<?php
/**
 * @category    AM
 * @package     AM_RevSlider
 * @copyright   Copyright (C) 2008-2013 ArexMage.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      ArexMage.com
 * @email       support@arexmage.com
 */
?>
<tr>
    <td colspan="2">
        <div>
            <div id="custom_animation_preview_wrapper" class="layer_animation_preview_wrapper">
                <div class="animation_preview_target">
                    <?php echo Mage::helper('revslider')->__('LAYER SAMPLE')?>
                </div>
            </div>
        </div>
        <?php if ($note = $this->getElement()->getNote()):?>
            <p class="note" id="note_delay" style="">
                <span><?php echo $note?></span>
            </p>
        <?php endif?>
    </td>
</tr>
<style type="text/css">
    table.form-list {width: 100%;}
</style>