<?php
/**
 * @category    AM
 * @package     AM_RevSlider
 * @copyright   Copyright (C) 2008-2013 ArexMage.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      ArexMage.com
 * @email       support@arexmage.com
 */
?>
<tr>
    <td class="label"></td>
    <td class="value" style="">
        <?php echo $this->getChildHtml('edit')?>
        <?php echo $this->getChildHtml('new')?>
    </td>
</tr>