<?php
/**
 * @category    AM
 * @package     AM_RevSlider
 * @copyright   Copyright (C) 2008-2013 ArexMage.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      ArexMage.com
 * @email       support@arexmage.com
 */
?>
<?php
$element = $this->getElement();
$id = $element->getHtmlId();
?>
<tr>
    <td colspan="2">
        <div style="width: 100%">
            <textarea style="" id="<?php echo $id ?>"></textarea>
        </div>
    </td>
</tr>
<script type="text/javascript">

</script>