<?php
/**
 * @category    AM
 * @package     AM_RevSlider
 * @copyright   Copyright (C) 2008-2013 ArexMage.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      ArexMage.com
 * @email       support@arexmage.com
 */
?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td class="value">
        <input
            id="<?php echo $this->getElement()->getHtmlId()?>"
            name="<?php echo $this->getElement()->getName()?>"
            value="<?php echo $this->getElement()->getValue()?>"
            title="<?php echo $this->getElement()->getTitle()?>"
            onclick="<?php echo $this->getElement()->getData('onclick')?>"
            onchange="<?php echo $this->getElement()->getData('onchange')?>"
            <?php if ($this->getElement()->getData('readonly') == true):?>readonly<?php endif ?>
            type="text"
            class="input-text"
            style="width:220px;vertical-align:top;"/>
        <?php echo  $this->getChildHtml('getBtn') ?>
        <?php if ($note = $this->getElement()->getData('note')):?>
            <p class="note" id="note_delay">
                <span><?php echo $note?></span>
            </p>
        <?php endif?>
    </td>
</tr>