<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * @see Mage_Reports_Block_Product_Viewed
 */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): $helpImg = $this->helper('ThemeOptionsBlacknwhite/images'); ?>
<div class="widget widget-viewed">
    <div class="block block-list">
        <div class="block-title">
            <strong><span><?php echo $this->__('Recently Viewed') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-images-list" id="widget-viewed-<?php echo $suffix; ?>">
            <?php foreach ($_products as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img <?php echo $helpImg->getImgSources($_product, 'small_image', 76, null); ?> alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('widget-viewed-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
<?php endif; ?>
