<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('header') ?>
<div class="content-wrapper">
    <div class="container_12">    
        <div class="main-container col3-layout">
            <div class="grid_12"><?php echo $this->getChildHtml('breadcrumbs') ?></div>
            <div class="clear"></div>
            <aside class="grid_3 sidebar sidebar-left">
				<?php echo $this->getChildHtml('left') ?>
            </aside>
            <div class="grid_6 col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
            <aside class="grid_3 sidebar sidebar-right">
                <?php echo $this->getChildHtml('right') ?>
            </aside>
            <div class="clear"></div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>