<?php
$meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
$meigee_blacknwhite_design = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_design');
$appearance = $meigee_blacknwhite_design['appearance'];
$toTop = $meigee_blacknwhite_general['otheroptions']['totop'];

/* Font Replacement */
if ($appearance['font_main'] == 1): 
	echo '<link href="http://fonts.googleapis.com/css?family=' . str_replace(' ', '+', $appearance['gfontmain']) . ':200,300,400,500,600,700,800" rel="stylesheet" type="text/css">';
endif;
if ($appearance['font'] == 1): 
	echo '<link href="http://fonts.googleapis.com/css?family=' . str_replace(' ', '+', $appearance['gfont']) . ':200,300,400,500,600,700,800" rel="stylesheet" type="text/css">';
endif;

/* toTop */
if ($toTop): ?>
	<script type="text/javascript">
		jQuery(window).load(function() {
			if(!((navigator.userAgent.match(/iPhone/i)) || (navigator.userAgent.match(/iPod/i)) || (navigator.userAgent.match(/iPad/i)) || (navigator.userAgent.match(/Android/i)))){
				jQuery().UItoTop({
					text: "<?php echo $this->__('Top'); ?>"
				});
			}
		});
	</script>
<?php endif;